apiVersion: v1
kind: Service
metadata:
  name: ship-fuel-prediction-service
spec:
  selector:
    app: ship-fuel-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
